using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace SUNRUSE.Prompter.Hosting.Tests
{
    public sealed class TimeoutTests
    {
        public sealed class DisposableMock : IDisposable
        {
            public int DisposedTimes = 0;

            public void Dispose()
            {
                DisposedTimes++;
            }
        }

        public enum TestAction
        {
            Reset,
            UnderIntervalDelay,
            OverIntervalDelay,
            Dispose
        }

        [Theory, Trait("Type", "Integration")]
        [InlineData(false)]
        [InlineData(false, TestAction.Reset)]
        [InlineData(false, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose)]
        [InlineData(false, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(false, TestAction.Reset, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(false, TestAction.Reset, TestAction.Reset, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(false, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose)]
        public async Task Integration(bool disposed, params TestAction[] actions)
        {
            var disposable = new DisposableMock();
            using (var timeout = new Timeout(TimeSpan.FromMilliseconds(100), disposable))
            {
                foreach (var action in actions)
                {
                    switch (action)
                    {
                        case TestAction.Reset: timeout.Reset(); break;
                        case TestAction.UnderIntervalDelay: await Task.Delay(50); break;
                        case TestAction.OverIntervalDelay: await Task.Delay(150); break;
                        case TestAction.Dispose: timeout.Dispose(); break;
                        default: throw new NotImplementedException();
                    }
                }

                Assert.Equal(disposed ? 1 : 0, disposable.DisposedTimes);
            }
        }

        [Theory, Trait("Type", "Fuzz")]
        [InlineData(false)]
        [InlineData(false, TestAction.Reset)]
        [InlineData(false, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose)]
        [InlineData(false, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(false, TestAction.Reset, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(false, TestAction.Reset, TestAction.Reset, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Reset, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.Reset)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose, TestAction.Reset)]
        [InlineData(false, TestAction.Reset, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(false, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(false, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Reset, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Reset, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Reset, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Reset, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Reset, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.UnderIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.OverIntervalDelay, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose)]
        [InlineData(true, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose, TestAction.Dispose)]
        public async Task Fuzz(bool disposed, params TestAction[] actions)
        {
            await Task.WhenAll(Enumerable.Range(0, 150).Select(async i =>
            {
                var disposable = new DisposableMock();
                using (var timeout = new Timeout(TimeSpan.FromMilliseconds(100), disposable))
                {
                    foreach (var action in actions)
                    {
                        switch (action)
                        {
                            case TestAction.Reset: timeout.Reset(); break;
                            case TestAction.UnderIntervalDelay: await Task.Delay(50); break;
                            case TestAction.OverIntervalDelay: await Task.Delay(150); break;
                            case TestAction.Dispose: timeout.Dispose(); break;
                            default: throw new NotImplementedException();
                        }
                    }

                    Assert.Equal(disposed ? 1 : 0, disposable.DisposedTimes);
                }
            }));
        }
    }
}
